### ISSUE TITLE
Upgrade extension to NetLogo 6

### ISSUE THREAD

**Issue by juanluck** [NetLogo/Landscapes-Extension#3]
Hi, 

your demo _landscape.nlogo_ seems to have some compatibility issues with Netlogo 6.0.

Thanks.

**Comment by nicolaspayette** [comment]
Thanks for reporting, @juanluck! You are right... but it's not just the demo. The whole extension needs to be upgraded to NetLogo 6. I'll see if I can give it a shot in the near future.

**Comment by nicolaspayette** [comment]
Upgraded. You can download the new version from here: https://github.com/NetLogo/Landscapes-Extension/releases/tag/v1.0.1

Let me know if you run into any trouble.

**Comment by juanluck** [comment]
That was fast!  
 I am playing with the demo a bit and looks great! Thanks :+1:

**Comment by nicolaspayette** [comment]
I had already started the upgrading work back in the beta days of 6.0. There wasn't much left to do. :-)
